### ISSUE TITLE
unable to create cluster

### ISSUE THREAD

**Issue by krithikagopalakrishnan** [pinterest/rocksplicator#188]
Hi all, 
im trying to get to know the rocksplicator setup. I configured the docker and trying to create a new cluster and im getting connection time out error.

```
> No handlers could be found for logger "kazoo.client"
> Traceback (most recent call last):
>   File "rocksdb_admin.py", line 114, in <module>
>     zk_client = _get_zk_client()
>   File "rocksdb_admin.py", line 110, in _get_zk_client
>     c.start()
>   File "/usr/local/lib/python2.7/dist-packages/kazoo/client.py", line 567, in start
>     raise self.handler.timeout_exception("Connection time-out")
> kazoo.handlers.threading.KazooTimeoutError: Connection time-out
> 
```

can someone help me in this..?

**Comment by newpoo** [comment]
Did you have the correct ZK cluster address specified in the script?

**Comment by krithikagopalakrishnan** [comment]
Thanks @newpoo  there was a typo in zk cluster address. Not sure how i overlooked it. 
Now the rocksdb_admin.py script runs successfully.
To understand the replication setup, im trying to run the counter service example. I landed into the following error, 
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0122 07:49:06.178100  2425 availability_zone.cpp:69] Got invalid az: 
I0122 07:49:06.187491  2430 thrift_client_pool.h:147] Started counter::CounterAsyncClient thrift client IO thread
I0122 07:49:06.187544  2431 thrift_client_pool.h:147] Started counter::CounterAsyncClient thrift client IO thread
I0122 07:49:06.187544  2429 thrift_client_pool.h:147] Started counter::CounterAsyncClient thrift client IO thread
I0122 07:49:06.187575  2428 thrift_client_pool.h:147] Started counter::CounterAsyncClient thrift client IO thread
E0122 07:49:06.187916  2432 file_watcher.cpp:196] Failed to inotify_add_watch() with errno 2 : No such file or directory
F0122 07:49:06.188069  2425 thrift_router.h:118] Check failed: common::FileWatcher::Instance()->AddFile( config_path_, [this, local_group] (std::string content) { std::shared_ptr<const ClusterLayout> new_layout( parser_(std::move(content), local_group)); { folly::RWSpinLock::WriteHolder write_guard(layout_rwlock_); cluster_layout_.swap(new_layout); } }) Failed to watch 
*** Check failure stack trace: ***
Aborted
```
Am i missing anything here? Anyother configuration has to be done beforehand??
Thanks in advance

**Comment by newpoo** [comment]
Can you try to pass the config file to --shard_config_path?
The cluster needs this config file to know how to route traffic from clients.

**Comment by krithikagopalakrishnan** [comment]
Hi @newpoo The server runs now. Now Im trying to write a small client program.
In that, Im creating a replicator instance and adding a db.
When i try to compile im getting the following error, 
```
../../rocksdb_replicator/librocksdb_replicator.a(replicated_db.cpp.o):(.data.rel.ro+0x10): undefined reference to `typeinfo for rocksdb::WriteBatch::Handler'
collect2: error: ld returned 1 exit status

```
What am i missing here?
Also, Through the client program, if i insert a batch, how does it gets replicated between shards??  Can u explain how replication occurs?

**Comment by newpoo** [comment]
What build system do you use? cmake?
